//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMIP.UniversalScan.Connector.USMSConnectorShared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IMIP.UniversalScan.Connector.USMSConnectorShared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cached Metadata.
        /// </summary>
        internal static string Menu_ClearCachedMetadata {
            get {
                return ResourceManager.GetString("Menu_ClearCachedMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Batch Waiting For Rescan.
        /// </summary>
        internal static string Menu_GetBatchForRescan {
            get {
                return ResourceManager.GetString("Menu_GetBatchForRescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting....
        /// </summary>
        internal static string Menu_Setting {
            get {
                return ResourceManager.GetString("Menu_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch {0} cannot be found.
        /// </summary>
        internal static string Msg_BatchNotFound {
            get {
                return ResourceManager.GetString("Msg_BatchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application cannot access the AD domain {0} to retrieve its AD groups. \nThe error is: {1} If this problem persist, please contact your administrator..
        /// </summary>
        internal static string Msg_CannotAccessAD {
            get {
                return ResourceManager.GetString("Msg_CannotAccessAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot be blank.
        /// </summary>
        internal static string Msg_CannotBlank {
            get {
                return ResourceManager.GetString("Msg_CannotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot check out batch {0} for processing.
        /// </summary>
        internal static string Msg_CannotCheckOut {
            get {
                return ResourceManager.GetString("Msg_CannotCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type {0} cannot be found.
        /// </summary>
        internal static string Msg_DocTypeNotFound {
            get {
                return ResourceManager.GetString("Msg_DocTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The global parameterset version {0} is not supported. Please contact your administrator.
        /// </summary>
        internal static string Msg_GlobalParameterVersionNotSupported {
            get {
                return ResourceManager.GetString("Msg_GlobalParameterVersionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient license for {0} to create or update the document. Please contact your administrator..
        /// </summary>
        internal static string Msg_InsufficientLicense {
            get {
                return ResourceManager.GetString("Msg_InsufficientLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume license for {0} not avaiable or insufficient. Please contact your administrator..
        /// </summary>
        internal static string Msg_NoLicense {
            get {
                return ResourceManager.GetString("Msg_NoLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global parameterset activity is not correct, please inform the administrator!.
        /// </summary>
        internal static string Msg_WrongParameterVersion {
            get {
                return ResourceManager.GetString("Msg_WrongParameterVersion", resourceCulture);
            }
        }
    }
}
